// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySanXuatNongSan.Data;

#nullable disable

namespace QuanLySanXuatNongSan.Migrations
{
    [DbContext(typeof(NongSanDbContext))]
    [Migration("20260322160359_TaoCSDL")]
    partial class TaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.ChiTietHoaDonXuat", b =>
                {
                    b.Property<int>("HoaDonXuatID")
                        .HasColumnType("int");

                    b.Property<int>("GiongCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<double>("SoLuong")
                        .HasColumnType("float");

                    b.HasKey("HoaDonXuatID", "GiongCungCapID");

                    b.HasIndex("GiongCungCapID");

                    b.ToTable("ChiTietHoaDonXuat");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.GiongCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DacTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiNongSan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenGiong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiGianThuHoachDuKien")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("GiongCungCap");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.HoaDonXuat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiLapID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NguoiLapID");

                    b.ToTable("HoaDonXuat");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.KeHoachSanXuat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("ChiPhiDuKien")
                        .HasColumnType("float");

                    b.Property<int>("GiongCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("KhuVucTrongID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThuHoachDuKien")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiPhuTrachID")
                        .HasColumnType("int");

                    b.Property<double>("SanLuongDuKien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("GiongCungCapID");

                    b.HasIndex("KhuVucTrongID");

                    b.HasIndex("NguoiPhuTrachID");

                    b.ToTable("KeHoachSanXuat");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.KhuVucTrong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("LoaiDat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrangDat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("KhuVucTrong");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.NguoiDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.NhatKyChamSoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double?>("ChiPhiPhatSinh")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnhMinhHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("KeHoachSanXuatID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoLuongVatTu")
                        .HasColumnType("float");

                    b.Property<int?>("VatTuNongNghiepID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KeHoachSanXuatID");

                    b.HasIndex("VatTuNongNghiepID");

                    b.ToTable("NhatKyChamSoc");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.ThuHoach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ChatLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnhThuHoach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("KeHoachSanXuatID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThuHoach")
                        .HasColumnType("datetime2");

                    b.Property<double>("SanLuong")
                        .HasColumnType("float");

                    b.Property<double>("TyLeHaoHut")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("KeHoachSanXuatID");

                    b.ToTable("ThuHoach");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.VatTuNongNghiep", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiVatTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NhaCungCapID")
                        .HasColumnType("int");

                    b.Property<double>("SoLuongTon")
                        .HasColumnType("float");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("NhaCungCapID");

                    b.ToTable("VatTuNongNghiep");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.ChiTietHoaDonXuat", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.GiongCungCap", "GiongCungCap")
                        .WithMany()
                        .HasForeignKey("GiongCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanXuatNongSan.Data.HoaDonXuat", "HoaDonXuat")
                        .WithMany("ChiTietHoaDonXuat")
                        .HasForeignKey("HoaDonXuatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiongCungCap");

                    b.Navigation("HoaDonXuat");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.HoaDonXuat", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanXuatNongSan.Data.NguoiDung", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.KeHoachSanXuat", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.GiongCungCap", "GiongCungCap")
                        .WithMany()
                        .HasForeignKey("GiongCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanXuatNongSan.Data.KhuVucTrong", "KhuVucTrong")
                        .WithMany()
                        .HasForeignKey("KhuVucTrongID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanXuatNongSan.Data.NguoiDung", "NguoiPhuTrach")
                        .WithMany()
                        .HasForeignKey("NguoiPhuTrachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiongCungCap");

                    b.Navigation("KhuVucTrong");

                    b.Navigation("NguoiPhuTrach");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.NhatKyChamSoc", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.KeHoachSanXuat", "KeHoachSanXuat")
                        .WithMany()
                        .HasForeignKey("KeHoachSanXuatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLySanXuatNongSan.Data.VatTuNongNghiep", "VatTuNongNghiep")
                        .WithMany()
                        .HasForeignKey("VatTuNongNghiepID");

                    b.Navigation("KeHoachSanXuat");

                    b.Navigation("VatTuNongNghiep");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.ThuHoach", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.KeHoachSanXuat", "KeHoachSanXuat")
                        .WithMany()
                        .HasForeignKey("KeHoachSanXuatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeHoachSanXuat");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.VatTuNongNghiep", b =>
                {
                    b.HasOne("QuanLySanXuatNongSan.Data.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLySanXuatNongSan.Data.HoaDonXuat", b =>
                {
                    b.Navigation("ChiTietHoaDonXuat");
                });
#pragma warning restore 612, 618
        }
    }
}
